# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Student.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: install
      run: npm install
    - name: ci
      run: npm ci
    - name: test
      run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.service_id }}
            api_key: ${{ secrets.render_token }}
            wait_deploy: true 
